# Generated by Django 4.0.5 on 2022-06-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_project_landing_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='landing_page',
            field=models.ImageField(upload_to='landing_pages/'),
        ),
    ]
